###
# /api
GET http://localhost:8000/api
content-type: application/json

###
# Get users
GET http://localhost:8000/api/users
content-type: application/json

###
# create user
POST http://localhost:8000/api/users HTTP/1.1
content-type: application/json

{
    "name": "admin",
    "email": "admin@karya.com",
    "password": "password"
}