###
# /api
GET http://localhost:8000/api
content-type: application/json

###
# Get users
GET http://localhost:8000/api/users
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGthcnlhLmNvbSIsInVzZXJJZCI6ImJhNzFlNzQ3LTIzOWYtNGZhYi1hMGY5LTc1M2MzNGQxZjg3NyIsImlhdCI6MTU5ODQ1NjQwNCwiZXhwIjoxNTk4NDkyODA0fQ.LdPRRxDsyQuU2Rr_QdjqfOoMFuFAwqzKpjQY3RkyW10
###
# create user
POST http://localhost:8000/api/users
content-type: application/json

{
    "name": "engineer",
    "email": "enagineae@karya.com",
    "password": "password"
}

###
#login
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "admin@karya.com",
    "password": "password"
}

###
# Projects
GET http://localhost:8000/api/projects
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGthcnlhLmNvbSIsInVzZXJJZCI6ImJhNzFlNzQ3LTIzOWYtNGZhYi1hMGY5LTc1M2MzNGQxZjg3NyIsImlhdCI6MTU5ODQ1NjQwNCwiZXhwIjoxNTk4NDkyODA0fQ.LdPRRxDsyQuU2Rr_QdjqfOoMFuFAwqzKpjQY3RkyW10

###
#create post
POST http://localhost:8000/api/projects
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGthcnlhLmNvbSIsInVzZXJJZCI6ImJhNzFlNzQ3LTIzOWYtNGZhYi1hMGY5LTc1M2MzNGQxZjg3NyIsImlhdCI6MTU5ODQ1NjQwNCwiZXhwIjoxNTk4NDkyODA0fQ.LdPRRxDsyQuU2Rr_QdjqfOoMFuFAwqzKpjQY3RkyW10
content-type: application/json

{
    "name": "Karya Project 1",
    "description": "This is projects management system",
    "project_manager_id": 2
}

###
#single project
GET http://localhost:8000/api/projects/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGthcnlhLmNvbSIsInVzZXJJZCI6ImJhNzFlNzQ3LTIzOWYtNGZhYi1hMGY5LTc1M2MzNGQxZjg3NyIsImlhdCI6MTU5ODQ1NjQwNCwiZXhwIjoxNTk4NDkyODA0fQ.LdPRRxDsyQuU2Rr_QdjqfOoMFuFAwqzKpjQY3RkyW10
content-type: application/json


###
#Edit project
PUT http://localhost:8000/api/projects/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGthcnlhLmNvbSIsInVzZXJJZCI6ImJhNzFlNzQ3LTIzOWYtNGZhYi1hMGY5LTc1M2MzNGQxZjg3NyIsImlhdCI6MTU5ODQ1NjQwNCwiZXhwIjoxNTk4NDkyODA0fQ.LdPRRxDsyQuU2Rr_QdjqfOoMFuFAwqzKpjQY3RkyW10
content-type: application/json

{
    "name": "Karya Project 2",
    "description": "This is projects management system",
    "project_manager_id": 2
}

